#!/usr/bin/env bash
#install haproxy as load balancer and configure it

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 19470-web-01 34.239.163.194:80 check\n\tserver 19470-web-02 3.85.222.35:80 check" >> /etc/haproxy/haproxy.cfg 
sudo service haproxy restart
