#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# for the 9th iteration, displays Best School and then Hi

x=1
while [ $x -le 10 ]
do
	if [ $x -eq 9 ]
	then
        	echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
    x=$(( x + 1 ))
done
